Pipeline:
  name: docker_template

GitRepo:
  name: sampleRepo
  gitProvider: github
  path: jfrog/jfrog-pipelines-samples
  branches:
    include: {{gitBranch}}

artifactoryIntegration: art

Image:
  name: sampleImage
  sourceRepository: foo
  autoPull: false

DockerBuild:
  name: sampleBuild
  dockerImageName: pipelines.jfrog.io/templates-docker-local/dbp
  dockerFileName: Dockerfile
  dockerFileLocation: './.jfrog-pipelines/DockerBuildAndPush'
  dockerImageTag: ${run_number}

DockerPush:
  name: samplePush

BuildInfo:
  autoPublishBuildInfo: true
  name: sampleBuildInfo
